"""由 s16 網格資料自動產生論文的 Typst 表格（中文版與英文版）。

為什麼要自動產生：論文最常見、也最難查的錯誤是「圖是新的、表是舊的」。
這裡讓圖與表都從同一份 JSON 產生，資料一更新兩者一起變。

中英兩版**也從同一份資料產生**，所以不會出現「中文版更新了、英文版沒更新」
這種更難查的不一致。

用法：
  python make_table_typst.py            # 同時產生中文版與英文版
  python make_table_typst.py --lang en  # 只產生英文版

輸出：
  paper/tables/capacity.typ      （給 paper.typ 用）
  paper/tables/capacity_en.typ   （給 paper_en.typ 用）

沒有資料的格子寫「—」/「--」，不寫 0；未跑滿種子的格子不並入統計。
"""
import argparse
import datetime
import json
import pathlib
import statistics as st

HERE = pathlib.Path(__file__).resolve().parent
PROJ = HERE.parent
ML = PROJ / "ml"

NS = list(range(3, 11))
DS = list(range(1, 9))
SLICE_DEPTHS = [4, 6, 8]
MIN_SEEDS = 5

TXT = {
    "zh": {
        "out": "capacity.typ",
        "dash": "—",
        "slice_hdr": "*qubit 數* $n$",
        "slice_col": "*$L$ = %d*",
        "slice_cap": [
            "固定深度下，測試準確率隨 qubit 數的變化（五個種子的平均值；",
            "灰色小字為標準差）。$n = 3$ 偏低是結構性的——$8$ 個類別最少需要",
            "$3$ 個 qubit 的投影讀出，該點剛好打滿——因此主張寫成「自 $n = 4$ 起」。",
        ],
        "grid_cap": [
            "完整的 $(n, L)$ 網格：五個種子的測試準確率平均值，",
            "括號內為標準差。「—」表示該格未跑滿五個種子；未跑滿的格子不並入統計，",
            "以免單一種子的「標準差 $0$」與五個種子的標準差混為一談。",
        ],
        "note_auto": "本檔由 paper/make_table_typst.py 自動產生，請勿手動編輯。",
        "note_src": "資料來源：ml/out/s16_capacity_final_5seed.json",
        "note_stat": "產生時間：%s ｜ 跑滿 %d 個種子的格數：%d/%d ｜ partial=%s",
    },
    "en": {
        "out": "capacity_en.typ",
        "dash": "--",
        "slice_hdr": "*Qubits* $n$",
        "slice_col": "*$L$ = %d*",
        "slice_cap": [
            "Test accuracy as a function of qubit count at fixed circuit depth",
            "(mean over five seeds; the smaller grey value is the standard deviation).",
            "$n = 3$ is structurally low: eight classes require at least a three-qubit",
            "projective readout, so that point is exactly saturated. The claim is therefore",
            "stated as \"from $n = 4$ onward\".",
        ],
        "grid_cap": [
            "The complete $(n, L)$ grid: mean test accuracy over five seeds,",
            "with the standard deviation in parentheses. A dash means the cell does not have",
            "all five seeds; incomplete cells are excluded rather than pooled, so that a",
            "single-seed standard deviation of $0$ is never mixed with a five-seed one.",
        ],
        "note_auto": "Generated by paper/make_table_typst.py -- do not edit by hand.",
        "note_src": "Source: ml/out/s16_capacity_final_5seed.json",
        "note_stat": "Generated %s | cells with all %d seeds: %d/%d | partial=%s",
    },
}


def cell(rows, n, d, key="test_acc"):
    v = [r[key] for r in rows if r["n_qubit"] == n and r["depth"] == d]
    if len(v) < MIN_SEEDS:
        return None, None
    return sum(v) / len(v), st.stdev(v)


def emit(lang, rows, filled, stamp, partial):
    t = TXT[lang]
    L = []
    L.append("// " + t["note_auto"])
    L.append("// " + t["note_src"])
    L.append("// " + (t["note_stat"] % (stamp, MIN_SEEDS, filled, len(NS) * len(DS), partial)))
    L.append("")

    L.append("#figure(")
    L.append("  table(")
    L.append("    columns: %d," % (1 + len(SLICE_DEPTHS)))
    L.append("    table.header([%s], %s)," % (
        t["slice_hdr"], ", ".join("[" + (t["slice_col"] % d) + "]" for d in SLICE_DEPTHS)))
    for n in NS:
        cells = []
        for d in SLICE_DEPTHS:
            m, s = cell(rows, n, d)
            cells.append("[" + t["dash"] + "]" if m is None
                         else "[%.4f #text(size: 6.8pt, fill: gray)[+/- %.4f]]" % (m, s))
        L.append("    [$%d$], %s," % (n, ", ".join(cells)))
    L.append("  ),")
    L.append("  caption: [" + t["slice_cap"][0])
    for line in t["slice_cap"][1:]:
        L.append("    " + line)
    L.append("],")
    L.append(") <tab:slices>")
    L.append("")

    L.append("#figure(")
    L.append("  text(size: 7pt)[")
    L.append("    #table(")
    L.append("      columns: %d," % (1 + len(DS)))
    L.append("      table.header([$n$ / $L$], %s)," % ", ".join("[%d]" % d for d in DS))
    for n in NS:
        cells = []
        for d in DS:
            m, s = cell(rows, n, d)
            cells.append("[" + t["dash"] + "]" if m is None
                         else "[%.3f #text(size: 5.8pt, fill: gray)[(%.3f)]]" % (m, s))
        L.append("      [$%d$], %s," % (n, ", ".join(cells)))
    L.append("    )")
    L.append("  ],")
    L.append("  caption: [" + t["grid_cap"][0])
    for line in t["grid_cap"][1:]:
        L.append("    " + line)
    L.append("],")
    L.append(") <tab:grid>")
    L.append("")

    OUT = HERE / "tables" / t["out"]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(chr(10).join(L), encoding="utf-8")
    print("已寫出 %s（%d 行）" % (OUT.name, len(L)))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lang", choices=["zh", "en", "both"], default="both")
    a = ap.parse_args()

    data = json.loads((ML / "out" / "s16_capacity_final_5seed.json").read_text(encoding="utf-8"))
    rows = data["rows"]
    filled = sum(1 for n in NS for d in DS if cell(rows, n, d)[0] is not None)
    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    langs = ["zh", "en"] if a.lang == "both" else [a.lang]
    for lang in langs:
        emit(lang, rows, filled, stamp, data.get("partial"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
